// Essential College Football Teams for Logo Database
const essentialCollegeTeams = {
    // Major FBS Teams
    'Alabama': 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
    'Auburn': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
    'Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    'Georgia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
    'LSU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
    'Tennessee': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
    'Texas A&M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
    'Arkansas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
    'Ole Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
    'Mississippi St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
    'Mississippi State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
    
    'Ohio State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
    'Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
    'Penn State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
    'Michigan St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
    'Michigan State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
    'Nebraska': 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
    'Wisconsin': 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
    'Iowa': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
    'Minnesota': 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
    'Illinois': 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
    'Maryland': 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
    'Rutgers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
    'Purdue': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
    'Indiana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
    'Northwestern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
    
    'Clemson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
    'Florida St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
    'Florida State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
    'Miami': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
    'Virginia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
    'North Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    'NC State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
    'Duke': 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
    'Wake Forest': 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
    'Boston College': 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
    'Louisville': 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
    'Pittsburgh': 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
    'Pitt': 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
    'Syracuse': 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
    'Virginia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
    'Georgia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
    
    'Texas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
    'Oklahoma': 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
    'Oklahoma State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
    'TCU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    'Baylor': 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
    'Kansas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
    'Iowa State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
    'Kansas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
    'West Virginia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
    'Texas Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
    'BYU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
    'Cincinnati': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
    'Houston': 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
    'UCF': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
    
    'USC': 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
    'UCLA': 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
    'Oregon': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
    'Washington': 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
    'Oregon St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png',
    'Oregon State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png',
    'Washington St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png',
    'Washington State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png',
    'Utah': 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
    'Colorado': 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
    'Arizona': 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
    'Arizona St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
    'Arizona State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
    'Stanford': 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
    'California': 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png',
    
    'Notre Dame': 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
    'Navy': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
    'Army': 'https://a.espncdn.com/i/teamlogos/ncaa/500/349.png',
    'Air Force': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    
    // Common FBS Teams
    'Memphis': 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
    'Troy': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
    'Buffalo': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
    'Kent State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png',
    'New Hampshire': 'https://a.espncdn.com/i/teamlogos/ncaa/500/160.png',
    'Ball State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png',
    'Villanova': 'https://a.espncdn.com/i/teamlogos/ncaa/500/222.png',
    'Norfolk St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2450.png',
    'Norfolk State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2450.png',
    'Youngstown St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png',
    'Youngstown State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2754.png',
    'North Texas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
    'SMU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
    'Missouri St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png',
    'Missouri State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png',
    'Richmond': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2508.png',
    'N\'Western St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png',
    'Northwestern State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png',
    'Incarnate Word': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2271.png',
    'UTSA': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png',
    'Morgan St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png',
    'Morgan State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png',
    'Toledo': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png',
    'Arkansas St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2037.png',
    'Arkansas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2037.png',
    'UTEP': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',
    'South Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
    'USF': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
    'Liberty': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
    'Bowling Green': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2085.png',
    'MTSU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
    'Nevada': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
    'Alcorn St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    'Alcorn State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    'Merrimack': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2771.png',
    'Kennesaw St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
    'Kennesaw State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
    'E Kentucky': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2185.png',
    'Eastern Kentucky': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2185.png',
    'Marshall': 'https://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
    'Monmouth': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2405.png',
    'Charlotte': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
    'Ohio': 'https://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
    'Old Dominion': 'https://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
    'Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    'Rice': 'https://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
    
    // Additional common teams
    'C Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
    'Central Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
    'Hou Christian': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2264.png',
    'Houston Christian': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2264.png',
    'Towson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/119.png',
    'William & Mary': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2729.png',
    'Samford': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2549.png',
    'W Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png',
    'Western Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png',
    'GA Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2240.png',
    'Georgia Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2240.png',
    'Murray St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/93.png',
    'Murray State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/93.png',
    'Georgia St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
    'Georgia State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
    'App State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
    'Appalachian State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
    'Southern Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
    'Prairie View': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2220.png',
    'E Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png',
    'Eastern Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png',
    'UMass': 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
    'New Mexico St': 'https://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
    'New Mexico State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
    'Louisiana Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png',
    'East Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
    'ECU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
    'Coastal': 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
    'Coastal Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
    'UConn': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'Connecticut': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'Jax State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/55.png',
    'Jacksonville State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/55.png'
};

module.exports = essentialCollegeTeams;
